[package]
name = "trainyard" # ToDo
version = "0.1.0"
publish = false
authors = ["Mike Tasca <mic.tasca@gmail.com>"] # ToDo: you are the author ;)
edition = "2021"
exclude = ["dist", "build", "assets", "credits"]

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[features]
dev = [
    "bevy/dynamic_linking",
]

[dependencies]
bevy = { version = "0.15", default-features = false, features = [
    "bevy_asset",
    "bevy_winit",
    "bevy_render",
    "bevy_core_pipeline",
    "bevy_sprite",
    "bevy_text",
    "bevy_ui",
    "bevy_state",
    "png",
    "default_font",
    "multi_threaded",
] }
bevy_kira_audio = { version = "0.21" }
bevy_asset_loader = { version = "0.22" }
bevy_pkv = "0.12"
rand = { version = "0.8" }
partial_application = "0.2.1"
serde = { version = "1.0", features = ["derive"] }
bevy_tweening = "0.12"

# keep the following in sync with Bevy's dependencies
winit = { version = "0.30", default-features = false }
image = { version = "0.25", default-features = false }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.3", features = ["wasm_js"] }

[build-dependencies]
embed-resource = "1.4"
